## Causal Effect Learning

In [1]:
import numpy as np
import causaldm.causaldm.learners.Online.CMAB._env_realCMAB as env
data = env.get_movielens()

WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.


WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


FileNotFoundError: [Errno 2] No such file or directory: './causaldm/learners/Online/MovieLens_MTTS_1M.txt'

In [2]:
data.keys()

dict_keys(['Individual', 'Xs', 'mean_ri', 'standardized_Xs'])

In [4]:
data_ML = data['Individual']

In [5]:
data_ML.keys()

dict_keys([48, 53, 169, 202, 329, 331, 352, 411, 424, 524, 692, 699, 770, 839, 1010, 1019, 1051, 1068, 1120, 1137, 1181, 1203, 1242, 1244, 1246, 1264, 1266, 1274, 1285, 1317, 1340, 1383, 1422, 1447, 1470, 1579, 1639, 1671, 1676, 1741, 1748, 1780, 1880, 1912, 1920, 1926, 1941, 1943, 1980, 1988, 2010, 2015, 2063, 2073, 2092, 2105, 2181, 2453, 2507, 2544, 2793, 2820, 2857, 2909, 3029, 3067, 3272, 3280, 3285, 3336, 3389, 3391, 3410, 3462, 3483, 3507, 3539, 3589, 3618, 3626, 3648, 3650, 3681, 3705, 3778, 3808, 3824, 3884, 3934, 3942, 3999, 4016, 4048, 4064, 4089, 4169, 4186, 4305, 4344, 4425, 4482, 4510, 4578, 4682, 4802, 5074, 5107, 5220, 5317, 5367, 5387, 5394, 5433, 5504, 5511, 5614, 5627, 5636, 5643, 5682, 5759, 5763, 5795, 5812, 5831, 5880, 6016, 148, 149, 528, 678, 970, 1050, 1125, 1194, 1605, 1958, 2077, 2116, 2419, 2777, 2986, 3312, 3471, 3768, 3829, 4579, 5026, 5306, 5312, 5333, 5530, 5837, 5996, 302, 877, 1207, 1635, 1778, 2124, 3018, 3032, 3311, 3401, 3675, 4028, 4387, 4808, 5788

In [6]:
data_ML[48].keys()

dict_keys(['Phi', 'Comedy', 'Drama', 'Action', 'Thriller', 'Sci-Fi'])

In [7]:
data_ML[48]['Comedy']

{'complete':        user_id  movie_id  rating   age  Comedy  Drama  Action  Thriller  \
 4220        48    2355.0     4.0  25.0     1.0    0.0     0.0       0.0   
 14400       48    2918.0     4.0  25.0     1.0    0.0     0.0       0.0   
 16752       48    2791.0     4.0  25.0     1.0    0.0     0.0       0.0   
 20195       48    2797.0     4.0  25.0     1.0    0.0     0.0       0.0   
 21689       48    2321.0     3.0  25.0     1.0    0.0     0.0       0.0   
 ...        ...       ...     ...   ...     ...    ...     ...       ...   
 355916    48.0     450.0     3.0  25.0     1.0    0.0     0.0       0.0   
 361546    48.0    2926.0     2.0  25.0     1.0    0.0     0.0       0.0   
 379684    48.0    3477.0     3.0  25.0     1.0    0.0     0.0       0.0   
 380838    48.0     360.0     2.0  25.0     1.0    0.0     0.0       0.0   
 380966    48.0     516.0     3.0  25.0     1.0    0.0     0.0       0.0   
 
         Sci-Fi  gender_M  occupation_academic/educator  \
 4220       0.0

In [8]:
data_ML[48]['Drama']['complete']

user_id  movie_id  rating   age  Comedy  Drama  Action  Thriller  \
14          48    1193.0     4.0  25.0     0.0    1.0     0.0       0.0   
11057       48     919.0     4.0  25.0     0.0    1.0     0.0       0.0   
25871       48     527.0     5.0  25.0     0.0    1.0     0.0       0.0   
31166       48    1721.0     4.0  25.0     0.0    1.0     0.0       0.0   
40383       48     150.0     4.0  25.0     0.0    1.0     0.0       0.0   
...        ...       ...     ...   ...     ...    ...     ...       ...   
377598    48.0    3404.0     5.0  25.0     0.0    1.0     0.0       0.0   
378510    48.0     996.0     3.0  25.0     0.0    1.0     0.0       0.0   
379685    48.0    3477.0     3.0  25.0     0.0    1.0     0.0       0.0   
380598    48.0     280.0     3.0  25.0     0.0    1.0     0.0       0.0   
380967    48.0     516.0     3.0  25.0     0.0    1.0     0.0       0.0   

        Sci-Fi  gender_M  occupation_academic/educator  \
14         0.0       1.0                           0.0   
11057      0.0       1.0                           0.0   
25871      0.0       1.0                           0.0   
31166      0.0       1.0                           0.0   
40383      0.0       1.0                           0.0   
...        ...       ...                           ...   
377598     0.0       1.0                           0.0   
378510     0.0       1.0                           0.0   
379685     0.0       1.0                           0.0   
380598     0.0       1.0                           0.0   
380967     0.0       1.0                           0.0   

        occupation_college/grad student  occupation_executive/managerial  \
14                                  1.0                              0.0   
11057                               1.0                              0.0   
25871                               1.0                              0.0   
31166                               1.0                              0.0   
40383                               1.0                              0.0   
...                                 ...                              ...   
377598                              1.0                              0.0   
378510                              1.0                              0.0   
379685                              1.0                              0.0   
380598                              1.0                              0.0   
380967                              1.0                              0.0   

        occupation_other  occupation_technician/engineer  
14                   0.0                             0.0  
11057                0.0                             0.0  
25871                0.0                             0.0  
31166                0.0                             0.0  
40383                0.0                             0.0  
...                  ...                             ...  
377598               0.0                             0.0  
378510               0.0                             0.0  
379685               0.0                             0.0  
380598               0.0                             0.0  
380967               0.0                             0.0  

[152 rows x 15 columns]

In [118]:
userinfo_index = np.array([3,9,11,12,13,14])
data_ML[48]['Drama']['complete'].iloc[0,userinfo_index]

age                                25.0
gender_M                            1.0
occupation_college/grad student     1.0
occupation_executive/managerial     0.0
occupation_other                    0.0
occupation_technician/engineer      0.0
Name: 14, dtype: object

In [119]:
data_ML[48]['Drama']['Reward']

[[3.0, 4.0, 2.0, 5.0], [82, 45, 15, 10]]

In [120]:
users_index = data_ML.keys()
movie_generes = ['Comedy', 'Drama', 'Action', 'Thriller', 'Sci-Fi']

In [121]:
data_CEL = {}
 
# initialize the final data we'll use in Causal Effect Learning
for i in movie_generes:
    data_CEL[i] = None   

In [122]:
import pandas as pd
for movie_genere in movie_generes:
    for user in users_index:
        data_CEL[movie_genere] = pd.concat([data_CEL[movie_genere] , data_ML[user][movie_genere]['complete']])

In [123]:
len(data_CEL['Comedy'])

49563

In [66]:
len(data_CEL['Drama'])

48235

In [67]:
len(data_CEL['Action'])

32375

In [68]:
len(data_CEL['Thriller'])

25583

In [69]:
len(data_CEL['Sci-Fi'])

17407

In [70]:
len(np.unique(data_CEL['Comedy']['user_id'])) # the total number of users

175

In [71]:
users_index

dict_keys([48, 53, 169, 202, 329, 331, 352, 411, 424, 524, 692, 699, 770, 839, 1010, 1019, 1051, 1068, 1120, 1137, 1181, 1203, 1242, 1244, 1246, 1264, 1266, 1274, 1285, 1317, 1340, 1383, 1422, 1447, 1470, 1579, 1639, 1671, 1676, 1741, 1748, 1780, 1880, 1912, 1920, 1926, 1941, 1943, 1980, 1988, 2010, 2015, 2063, 2073, 2092, 2105, 2181, 2453, 2507, 2544, 2793, 2820, 2857, 2909, 3029, 3067, 3272, 3280, 3285, 3336, 3389, 3391, 3410, 3462, 3483, 3507, 3539, 3589, 3618, 3626, 3648, 3650, 3681, 3705, 3778, 3808, 3824, 3884, 3934, 3942, 3999, 4016, 4048, 4064, 4089, 4169, 4186, 4305, 4344, 4425, 4482, 4510, 4578, 4682, 4802, 5074, 5107, 5220, 5317, 5367, 5387, 5394, 5433, 5504, 5511, 5614, 5627, 5636, 5643, 5682, 5759, 5763, 5795, 5812, 5831, 5880, 6016, 148, 149, 528, 678, 970, 1050, 1125, 1194, 1605, 1958, 2077, 2116, 2419, 2777, 2986, 3312, 3471, 3768, 3829, 4579, 5026, 5306, 5312, 5333, 5530, 5837, 5996, 302, 877, 1207, 1635, 1778, 2124, 3018, 3032, 3311, 3401, 3675, 4028, 4387, 4808, 5788

In [124]:
data_CEL['Comedy']

user_id  movie_id  rating   age  Comedy  Drama  Action  Thriller  \
4220        48    2355.0     4.0  25.0     1.0    0.0     0.0       0.0   
14400       48    2918.0     4.0  25.0     1.0    0.0     0.0       0.0   
16752       48    2791.0     4.0  25.0     1.0    0.0     0.0       0.0   
20195       48    2797.0     4.0  25.0     1.0    0.0     0.0       0.0   
21689       48    2321.0     3.0  25.0     1.0    0.0     0.0       0.0   
...        ...       ...     ...   ...     ...    ...     ...       ...   
393463  5878.0    3299.0     3.0  25.0     1.0    0.0     0.0       0.0   
395410  5878.0     892.0     5.0  25.0     1.0    0.0     0.0       0.0   
396058  5878.0     574.0     1.0  25.0     1.0    0.0     0.0       0.0   
397794  5878.0    1812.0     5.0  25.0     1.0    0.0     0.0       0.0   
400719  5878.0    3830.0     1.0  25.0     1.0    0.0     0.0       0.0   

        Sci-Fi  gender_M  occupation_academic/educator  \
4220       0.0       1.0                           0.0   
14400      0.0       1.0                           0.0   
16752      0.0       1.0                           0.0   
20195      0.0       1.0                           0.0   
21689      0.0       1.0                           0.0   
...        ...       ...                           ...   
393463     0.0       0.0                           0.0   
395410     0.0       0.0                           0.0   
396058     0.0       0.0                           0.0   
397794     0.0       0.0                           0.0   
400719     0.0       0.0                           0.0   

        occupation_college/grad student  occupation_executive/managerial  \
4220                                1.0                              0.0   
14400                               1.0                              0.0   
16752                               1.0                              0.0   
20195                               1.0                              0.0   
21689                               1.0                              0.0   
...                                 ...                              ...   
393463                              0.0                              0.0   
395410                              0.0                              0.0   
396058                              0.0                              0.0   
397794                              0.0                              0.0   
400719                              0.0                              0.0   

        occupation_other  occupation_technician/engineer  
4220                 0.0                             0.0  
14400                0.0                             0.0  
16752                0.0                             0.0  
20195                0.0                             0.0  
21689                0.0                             0.0  
...                  ...                             ...  
393463               1.0                             0.0  
395410               1.0                             0.0  
396058               1.0                             0.0  
397794               1.0                             0.0  
400719               1.0                             0.0  

[49563 rows x 15 columns]

### the entire dataset of interst

In [125]:
data_CEL_all = data_CEL['Comedy']
for movie_genere in movie_generes[1:5]:
    data_CEL_all = pd.concat([data_CEL_all, data_CEL[movie_genere]])

In [126]:
len(data_CEL_all)

173163

In [127]:
data_CEL_all.iloc[np.where(data_CEL_all['Comedy']==1)[0],userinfo_index]

age  gender_M  occupation_college/grad student  \
4220    25.0       1.0                              1.0   
14400   25.0       1.0                              1.0   
16752   25.0       1.0                              1.0   
20195   25.0       1.0                              1.0   
21689   25.0       1.0                              1.0   
...      ...       ...                              ...   
393463  25.0       0.0                              0.0   
395410  25.0       0.0                              0.0   
396058  25.0       0.0                              0.0   
397794  25.0       0.0                              0.0   
400719  25.0       0.0                              0.0   

        occupation_executive/managerial  occupation_other  \
4220                                0.0               0.0   
14400                               0.0               0.0   
16752                               0.0               0.0   
20195                               0.0               0.0   
21689                               0.0               0.0   
...                                 ...               ...   
393463                              0.0               1.0   
395410                              0.0               1.0   
396058                              0.0               1.0   
397794                              0.0               1.0   
400719                              0.0               1.0   

        occupation_technician/engineer  
4220                               0.0  
14400                              0.0  
16752                              0.0  
20195                              0.0  
21689                              0.0  
...                                ...  
393463                             0.0  
395410                             0.0  
396058                             0.0  
397794                             0.0  
400719                             0.0  

[49563 rows x 6 columns]

### sample 1% of the data by users

In [108]:
len(data_CEL['Comedy'])

25583

In [128]:
np.where(data_CEL['Action']['user_id'] == user)[0]

array([32285, 32286, 32287, 32288, 32289, 32290, 32291, 32292, 32293,
       32294, 32295, 32296, 32297, 32298, 32299, 32300, 32301, 32302,
       32303, 32304, 32305, 32306, 32307, 32308, 32309, 32310, 32311,
       32312, 32313, 32314, 32315, 32316, 32317, 32318, 32319, 32320,
       32321, 32322, 32323, 32324, 32325, 32326, 32327, 32328, 32329,
       32330, 32331, 32332, 32333, 32334, 32335, 32336, 32337, 32338,
       32339, 32340, 32341, 32342, 32343, 32344, 32345, 32346, 32347,
       32348, 32349, 32350, 32351, 32352, 32353, 32354, 32355, 32356,
       32357, 32358, 32359, 32360, 32361, 32362, 32363, 32364, 32365,
       32366, 32367, 32368, 32369, 32370, 32371, 32372, 32373, 32374])

In [135]:
int(np.ceil(10.5))

11

In [139]:
random.sample(np.array([1,2,3]),2)

TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

In [137]:
import random
random.sample(np.where(data_CEL['Action']['user_id'] == user)[0], int(np.ceil(len(np.where(data_CEL['Action']['user_id'] == user)[0]))))


TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

In [116]:
# randomly select 1% of samples from all users
data_CEL_sample = data_CEL['Comedy']
for movie_genere in movie_generes[1:5]:

    data_CEL_sample = pd.concat([data_CEL_sample, data_CEL[movie_genere]])


for user in users_index:       
    len(np.where(data_CEL['Action']['user_id'] == user)[0])
    


In [115]:
for user in users_index:
    print(user)

48
53
169
202
329
331
352
411
424
524
692
699
770
839
1010
1019
1051
1068
1120
1137
1181
1203
1242
1244
1246
1264
1266
1274
1285
1317
1340
1383
1422
1447
1470
1579
1639
1671
1676
1741
1748
1780
1880
1912
1920
1926
1941
1943
1980
1988
2010
2015
2063
2073
2092
2105
2181
2453
2507
2544
2793
2820
2857
2909
3029
3067
3272
3280
3285
3336
3389
3391
3410
3462
3483
3507
3539
3589
3618
3626
3648
3650
3681
3705
3778
3808
3824
3884
3934
3942
3999
4016
4048
4064
4089
4169
4186
4305
4344
4425
4482
4510
4578
4682
4802
5074
5107
5220
5317
5367
5387
5394
5433
5504
5511
5614
5627
5636
5643
5682
5759
5763
5795
5812
5831
5880
6016
148
149
528
678
970
1050
1125
1194
1605
1958
2077
2116
2419
2777
2986
3312
3471
3768
3829
4579
5026
5306
5312
5333
5530
5837
5996
302
877
1207
1635
1778
2124
3018
3032
3311
3401
3675
4028
4387
4808
5788
1764
2012
3823
4140
4411
5878


### nonlinear model fitting

In [76]:

models_CEL = {}
 
# initialize the models we'll fit in Causal Effect Learning
for i in movie_generes:
    models_CEL[i] = None   



In [77]:
from lightgbm import LGBMRegressor
for movie_genere in movie_generes: 
    models_CEL[movie_genere] = LGBMRegressor(max_depth=3)
    models_CEL[movie_genere].fit(data_CEL_all.iloc[np.where(data_CEL_all[movie_genere]==1)[0],userinfo_index],data_CEL_all.iloc[np.where(data_CEL_all[movie_genere]==1)[0],2] )


In [78]:
models_CEL['Comedy'].predict(data_CEL_all.iloc[np.where(data_CEL_all['Comedy']==1)[0],userinfo_index])

array([3.1721, 3.1721, 3.1721, ..., 3.5565, 3.5565, 3.5565])

In [79]:
min(data_CEL_all['age'])

16.0

In [80]:
max(data_CEL_all['age'])

56.0

In [81]:
# record thev estimated expected reward for each movie genere, under each possible combination of state variable
age_range = np.linspace(min(data_CEL_all['age']),max(data_CEL_all['age']),int(max(data_CEL_all['age'])-min(data_CEL_all['age'])+1)).astype(int)
print(age_range)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56]


In [82]:
import itertools

gender = np.array([0,1])
occupation_college = np.array([0,1])
occupation_executive = np.array([0,1])
occupation_other  = np.array([0,1])
occupation_technician = np.array([0,1])

# result contains all possible combinations.
combinations = pd.DataFrame(itertools.product(age_range,gender,occupation_college,
                                              occupation_executive,occupation_other,occupation_technician))

In [83]:
combinations.columns =['age','gender','occupation_college', 'occupation_executive','occupation_other','occupation_technician']
combinations

age  gender  occupation_college  occupation_executive  occupation_other  \
0      16       0                   0                     0                 0   
1      16       0                   0                     0                 0   
2      16       0                   0                     0                 1   
3      16       0                   0                     0                 1   
4      16       0                   0                     1                 0   
...   ...     ...                 ...                   ...               ...   
1307   56       1                   1                     0                 1   
1308   56       1                   1                     1                 0   
1309   56       1                   1                     1                 0   
1310   56       1                   1                     1                 1   
1311   56       1                   1                     1                 1   

      occupation_technician  
0                         0  
1                         1  
2                         0  
3                         1  
4                         0  
...                     ...  
1307                      1  
1308                      0  
1309                      1  
1310                      0  
1311                      1  

[1312 rows x 6 columns]

In [84]:
len(models_CEL['Comedy'].predict(combinations))

1312

In [85]:
movie_genere

'Sci-Fi'

In [86]:
models_CEL['Comedy'].predict(combinations)

array([3.6671, 3.3669, 3.7403, ..., 3.1545, 3.7169, 2.7921])

In [87]:
values = np.zeros((5,1312))
i=0
for movie_genere in movie_generes:
    values[i,:] = models_CEL[movie_genere].predict(combinations)
    i=i+1
    print(values)

[[3.6671 3.3669 3.7403 ... 3.1545 3.7169 2.7921]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]]
[[3.6671 3.3669 3.7403 ... 3.1545 3.7169 2.7921]
 [4.1591 3.8884 4.323  ... 3.617  4.1462 3.623 ]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]]
[[3.6671 3.3669 3.7403 ... 3.1545 3.7169 2.7921]
 [4.1591 3.8884 4.323  ... 3.617  4.1462 3.623 ]
 [3.621  3.6609 3.7536 ... 3.8367 3.9265 3.7139]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]]
[[3.6671 3.3669 3.7403 ... 3.1545 3.7169 2.7921]
 [4.1591 3.8884 4.323  ... 3.617  4.1462 3.623 ]
 [3.621  3.6609 3.7536 ... 3.8367 3.9265 3.7139]
 [3.8914 3.8843 3.931  ... 3.6474 4.428  3.5516]
 [0.     0.     0.     ... 0.     0.     0.    ]]
[[3.6671 3.3669 

In [88]:
result_CEL = combinations
i=0
for movie_genere in movie_generes:
  #values = models_CEL[movie_genere].predict(combinations)
  result_CEL.insert(len(result_CEL.columns), movie_genere, values[i,:])
  i=i+1

In [89]:
result_CEL

age  gender  occupation_college  occupation_executive  occupation_other  \
0      16       0                   0                     0                 0   
1      16       0                   0                     0                 0   
2      16       0                   0                     0                 1   
3      16       0                   0                     0                 1   
4      16       0                   0                     1                 0   
...   ...     ...                 ...                   ...               ...   
1307   56       1                   1                     0                 1   
1308   56       1                   1                     1                 0   
1309   56       1                   1                     1                 0   
1310   56       1                   1                     1                 1   
1311   56       1                   1                     1                 1   

      occupation_technician    Comedy     Drama    Action  Thriller    Sci-Fi  
0                         0  3.667108  4.159101  3.621042  3.891404  3.579256  
1                         1  3.366861  3.888376  3.660929  3.884298  3.406647  
2                         0  3.740314  4.323008  3.753576  3.930968  3.621002  
3                         1  3.432508  4.036827  3.793464  3.923861  3.460696  
4                         0  3.654633  4.138223  3.807868  3.984900  3.545622  
...                     ...       ...       ...       ...       ...       ...  
1307                      1  2.783766  3.636899  3.261385  3.142084  2.852911  
1308                      0  4.108480  4.215949  4.049312  4.523752  4.236776  
1309                      1  3.154513  3.617045  3.836742  3.647366  3.096732  
1310                      0  3.716872  4.146200  3.926512  4.428002  4.102457  
1311                      1  2.792068  3.623021  3.713942  3.551617  2.962412  

[1312 rows x 11 columns]

In [90]:
result_CEL.to_csv('/Users/alinaxu/Documents/CDM/Causal-Decision-Making/5_Case_Study/MovieLens/result_CEL_nonlinear.csv')

In [91]:
# read the result file
result_CEL_nonlinear = pd.read_csv('/Users/alinaxu/Documents/CDM/Causal-Decision-Making/5_Case_Study/MovieLens/result_CEL_nonlinear.csv')
result_CEL_nonlinear = result_CEL_nonlinear.drop(result_CEL_nonlinear.columns[0], axis=1)
result_CEL_nonlinear

age  gender  occupation_college  occupation_executive  occupation_other  \
0      16       0                   0                     0                 0   
1      16       0                   0                     0                 0   
2      16       0                   0                     0                 1   
3      16       0                   0                     0                 1   
4      16       0                   0                     1                 0   
...   ...     ...                 ...                   ...               ...   
1307   56       1                   1                     0                 1   
1308   56       1                   1                     1                 0   
1309   56       1                   1                     1                 0   
1310   56       1                   1                     1                 1   
1311   56       1                   1                     1                 1   

      occupation_technician    Comedy     Drama    Action  Thriller    Sci-Fi  
0                         0  3.667108  4.159101  3.621042  3.891404  3.579256  
1                         1  3.366861  3.888376  3.660929  3.884298  3.406647  
2                         0  3.740314  4.323008  3.753576  3.930968  3.621002  
3                         1  3.432508  4.036827  3.793464  3.923861  3.460696  
4                         0  3.654633  4.138223  3.807868  3.984900  3.545622  
...                     ...       ...       ...       ...       ...       ...  
1307                      1  2.783766  3.636899  3.261385  3.142084  2.852911  
1308                      0  4.108480  4.215949  4.049312  4.523752  4.236776  
1309                      1  3.154513  3.617045  3.836742  3.647366  3.096732  
1310                      0  3.716872  4.146200  3.926512  4.428002  4.102457  
1311                      1  2.792068  3.623021  3.713942  3.551617  2.962412  

[1312 rows x 11 columns]

#### Analysis

In [92]:
np.where(result_CEL_nonlinear['gender']==0)[0]

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   32,   33,   34,   35,   36,   37,
         38,   39,   40,   41,   42,   43,   44,   45,   46,   47,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   96,   97,   98,   99,  100,  101,  102,
        103,  104,  105,  106,  107,  108,  109,  110,  111,  128,  129,
        130,  131,  132,  133,  134,  135,  136,  137,  138,  139,  140,
        141,  142,  143,  160,  161,  162,  163,  164,  165,  166,  167,
        168,  169,  170,  171,  172,  173,  174,  175,  192,  193,  194,
        195,  196,  197,  198,  199,  200,  201,  202,  203,  204,  205,
        206,  207,  224,  225,  226,  227,  228,  229,  230,  231,  232,
        233,  234,  235,  236,  237,  238,  239,  256,  257,  258,  259,
        260,  261,  262,  263,  264,  265,  266,  267,  268,  269,  270,
        271,  288,  289,  290,  291,  292,  293,  2

In [93]:
result_CEL_nonlinear.iloc[np.where(result_CEL_nonlinear['gender']==0)[0],6:11]

Comedy     Drama    Action  Thriller    Sci-Fi
0     3.667108  4.159101  3.621042  3.891404  3.579256
1     3.366861  3.888376  3.660929  3.884298  3.406647
2     3.740314  4.323008  3.753576  3.930968  3.621002
3     3.432508  4.036827  3.793464  3.923861  3.460696
4     3.654633  4.138223  3.807868  3.984900  3.545622
...        ...       ...       ...       ...       ...
1291  2.794232  3.697612  3.391132  3.328777  2.938607
1292  4.212522  4.417237  4.849207  4.435471  4.563120
1293  3.317231  3.961143  4.636637  4.194262  3.491331
1294  3.722974  4.234974  4.241653  3.736452  4.258903
1295  2.856846  3.854605  4.029084  3.495243  3.199417

[656 rows x 5 columns]

In [94]:
# calculate the expected reward of Comedy for female
TE_female=result_CEL_nonlinear.iloc[np.where(result_CEL_nonlinear['gender']==0)[0],6:11]/(41*(2**4))
TE_female=pd.DataFrame(TE_female.sum(axis=0))
TE_female.columns =['Expected Rating']

In [95]:
TE_female

Expected Rating
Comedy           3.474339
Drama            3.830191
Action           3.666765
Thriller         3.599922
Sci-Fi           3.379801

In [96]:
# calculate the expected reward of Comedy for female
TE_male=result_CEL_nonlinear.iloc[np.where(result_CEL_nonlinear['gender']==1)[0],6:11]/(41*(2**4))
TE_male=pd.DataFrame(TE_male.sum(axis=0))
TE_male.columns =['Expected Rating']

In [97]:
TE_male

Expected Rating
Comedy           3.337232
Drama            3.707185
Action           3.387759
Thriller         3.441026
Sci-Fi           3.325087

### linear model fitting

In [308]:

models_CEL_linear = {}
 
# initialize the models we'll fit in Causal Effect Learning
for i in movie_generes:
    models_CEL_linear[i] = None   



In [309]:
from sklearn.linear_model import LinearRegression
for movie_genere in movie_generes: 
    models_CEL_linear[movie_genere] = LinearRegression()
    models_CEL_linear[movie_genere].fit(data_CEL_all.iloc[np.where(data_CEL_all[movie_genere]==1)[0],userinfo_index],data_CEL_all.iloc[np.where(data_CEL_all[movie_genere]==1)[0],2] )


In [310]:
models_CEL_linear['Comedy'].predict(data_CEL_all.iloc[np.where(data_CEL_all['Comedy']==1)[0],userinfo_index])

array([3.243 , 3.243 , 3.243 , ..., 3.4266, 3.4266, 3.4266])

In [313]:
# record thev estimated expected reward for each movie genere, under each possible combination of state variable
age_range = np.linspace(min(data_CEL_all['age']),max(data_CEL_all['age']),int(max(data_CEL_all['age'])-min(data_CEL_all['age'])+1)).astype(int)
print(age_range)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56]


In [314]:
import itertools

gender = np.array([0,1])
occupation_college = np.array([0,1])
occupation_executive = np.array([0,1])
occupation_other  = np.array([0,1])
occupation_technician = np.array([0,1])

# result contains all possible combinations.
combinations = pd.DataFrame(itertools.product(age_range,gender,occupation_college,
                                              occupation_executive,occupation_other,occupation_technician))

In [315]:
combinations.columns =['age','gender','occupation_college', 'occupation_executive','occupation_other','occupation_technician']
combinations

age  gender  occupation_college  occupation_executive  occupation_other  \
0      16       0                   0                     0                 0   
1      16       0                   0                     0                 0   
2      16       0                   0                     0                 1   
3      16       0                   0                     0                 1   
4      16       0                   0                     1                 0   
...   ...     ...                 ...                   ...               ...   
1307   56       1                   1                     0                 1   
1308   56       1                   1                     1                 0   
1309   56       1                   1                     1                 0   
1310   56       1                   1                     1                 1   
1311   56       1                   1                     1                 1   

      occupation_technician  
0                         0  
1                         1  
2                         0  
3                         1  
4                         0  
...                     ...  
1307                      1  
1308                      0  
1309                      1  
1310                      0  
1311                      1  

[1312 rows x 6 columns]

In [316]:
values = np.zeros((5,1312))
i=0
for movie_genere in movie_generes:
  values[i,:] = models_CEL_linear[movie_genere].predict(combinations)
  i=i+1
  print(values)

[[3.4122 3.2197 3.4156 ... 3.0353 3.2311 3.0386]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]]
[[3.4122 3.2197 3.4156 ... 3.0353 3.2311 3.0386]
 [3.6734 3.5095 3.703  ... 3.2655 3.459  3.2951]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]]
[[3.4122 3.2197 3.4156 ... 3.0353 3.2311 3.0386]
 [3.6734 3.5095 3.703  ... 3.2655 3.459  3.2951]
 [3.2971 3.2555 3.3067 ... 3.1897 3.2409 3.1992]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]]
[[3.4122 3.2197 3.4156 ... 3.0353 3.2311 3.0386]
 [3.6734 3.5095 3.703  ... 3.2655 3.459  3.2951]
 [3.2971 3.2555 3.3067 ... 3.1897 3.2409 3.1992]
 [3.4948 3.4161 3.4481 ... 3.155  3.187  3.1083]
 [0.     0.     0.     ... 0.     0.     0.    ]]
[[3.4122 3.2197 

In [317]:
result_CEL_linear = combinations
i=0
for movie_genere in movie_generes:
  #values = models_CEL[movie_genere].predict(combinations)
  result_CEL_linear.insert(len(result_CEL_linear.columns), movie_genere, values[i,:])
  i=i+1

In [318]:
result_CEL_linear

age  gender  occupation_college  occupation_executive  occupation_other  \
0      16       0                   0                     0                 0   
1      16       0                   0                     0                 0   
2      16       0                   0                     0                 1   
3      16       0                   0                     0                 1   
4      16       0                   0                     1                 0   
...   ...     ...                 ...                   ...               ...   
1307   56       1                   1                     0                 1   
1308   56       1                   1                     1                 0   
1309   56       1                   1                     1                 0   
1310   56       1                   1                     1                 1   
1311   56       1                   1                     1                 1   

      occupation_technician    Comedy     Drama    Action  Thriller    Sci-Fi  
0                         0  3.412203  3.673359  3.297117  3.494783  3.286167  
1                         1  3.219698  3.509493  3.255487  3.416131  3.128323  
2                         0  3.415576  3.703012  3.306670  3.448094  3.259327  
3                         1  3.223072  3.539146  3.265040  3.369442  3.101483  
4                         0  3.359126  3.665731  3.404304  3.538511  3.253674  
...                     ...       ...       ...       ...       ...       ...  
1307                      1  3.091722  3.302749  3.092034  3.064599  2.972893  
1308                      0  3.227776  3.429334  3.231298  3.233668  3.125085  
1309                      1  3.035271  3.265468  3.189667  3.155016  2.967241  
1310                      0  3.231149  3.458987  3.240851  3.186979  3.098245  
1311                      1  3.038645  3.295121  3.199220  3.108327  2.940401  

[1312 rows x 11 columns]

In [319]:
result_CEL_linear.to_csv('drive/MyDrive/Causal-Decision-Making/Data-Demo/result_CEL_linear.csv')

In [320]:
# read the result file
result_CEL_linear = pd.read_csv('drive/MyDrive/Causal-Decision-Making/Data-Demo/result_CEL_linear.csv')
result_CEL_linear = result_CEL_linear.drop(result_CEL_linear.columns[0], axis=1)
result_CEL_linear

age  gender  occupation_college  occupation_executive  occupation_other  \
0      16       0                   0                     0                 0   
1      16       0                   0                     0                 0   
2      16       0                   0                     0                 1   
3      16       0                   0                     0                 1   
4      16       0                   0                     1                 0   
...   ...     ...                 ...                   ...               ...   
1307   56       1                   1                     0                 1   
1308   56       1                   1                     1                 0   
1309   56       1                   1                     1                 0   
1310   56       1                   1                     1                 1   
1311   56       1                   1                     1                 1   

      occupation_technician    Comedy     Drama    Action  Thriller    Sci-Fi  
0                         0  3.412203  3.673359  3.297117  3.494783  3.286167  
1                         1  3.219698  3.509493  3.255487  3.416131  3.128323  
2                         0  3.415576  3.703012  3.306670  3.448094  3.259327  
3                         1  3.223072  3.539146  3.265040  3.369442  3.101483  
4                         0  3.359126  3.665731  3.404304  3.538511  3.253674  
...                     ...       ...       ...       ...       ...       ...  
1307                      1  3.091722  3.302749  3.092034  3.064599  2.972893  
1308                      0  3.227776  3.429334  3.231298  3.233668  3.125085  
1309                      1  3.035271  3.265468  3.189667  3.155016  2.967241  
1310                      0  3.231149  3.458987  3.240851  3.186979  3.098245  
1311                      1  3.038645  3.295121  3.199220  3.108327  2.940401  

[1312 rows x 11 columns]

#### Analysis

In [322]:
result_CEL_linear.iloc[np.where(result_CEL_linear['gender']==0)[0],6:11]

Comedy     Drama    Action  Thriller    Sci-Fi
0     3.412203  3.673359  3.297117  3.494783  3.286167
1     3.219698  3.509493  3.255487  3.416131  3.128323
2     3.415576  3.703012  3.306670  3.448094  3.259327
3     3.223072  3.539146  3.265040  3.369442  3.101483
4     3.359126  3.665731  3.404304  3.538511  3.253674
...        ...       ...       ...       ...       ...
1291  3.205060  3.347510  3.158682  3.172299  2.983469
1292  3.341114  3.474094  3.297946  3.341368  3.135660
1293  3.148609  3.310228  3.256316  3.262715  2.977817
1294  3.344487  3.503747  3.307499  3.294679  3.108820
1295  3.151983  3.339881  3.265868  3.216027  2.950977

[656 rows x 5 columns]

In [323]:
# calculate the expected reward of Comedy for female
TE_female_linear=result_CEL_linear.iloc[np.where(result_CEL_linear['gender']==0)[0],6:11]/(41*(2**4))
TE_female_linear=pd.DataFrame(TE_female_linear.sum(axis=0))
TE_female_linear.columns =['Expected Rating']

In [324]:
TE_female_linear

Expected Rating
Comedy           3.282093
Drama            3.506620
Action           3.281493
Thriller         3.355405
Sci-Fi           3.118572

In [326]:
# calculate the expected reward of Comedy for female
TE_male_linear=result_CEL_linear.iloc[np.where(result_CEL_linear['gender']==1)[0],6:11]/(41*(2**4))
TE_male_linear=pd.DataFrame(TE_male_linear.sum(axis=0))
TE_male_linear.columns =['Expected Rating']

In [327]:
TE_male_linear

Expected Rating
Comedy           3.168755
Drama            3.461860
Action           3.214845
Thriller         3.247705
Sci-Fi           3.107996