### **1. S-learner**


The first estimator we would like to introduce is the S-learner, also known as a ``single learner". This is one of the most foundamental learners in HTE esitmation, and is very easy to implement.

Under three common assumptions in causal inference, i.e. (1) consistency, (2) no unmeasured confounders (NUC), (3) positivity assumption, the heterogeneous treatment effect can be identified by the observed data, where
\begin{equation*}
\tau(s)=\mathbb{E}[R|S,A=1]-\mathbb{E}[R|S,A=0].
\end{equation*}

The basic idea of S-learner is to fit a model for $\mathbb{E}[R|S,A]$, and then construct a plug-in estimator based on the expression above. Specifically, the algorithm can be summarized as below:

**Step 1:**  Estimate the combined response function $\mu(s,a):=\mathbb{E}[R|S=s,A=a]$ with any regression algorithm or supervised machine learning methods;

**Step 2:**  Estimate HTE by 
\begin{equation*}
\hat{\tau}_{\text{S-learner}}(s)=\hat\mu(s,1)-\hat\mu(s,0).
\end{equation*}




In [1]:
# import related packages
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt;
from lightgbm import LGBMRegressor;
from sklearn.linear_model import LinearRegression

### Mimic3 Data

In [2]:
# Get data
n = 5000
selected = ['Glucose','paO2','PaO2_FiO2',  'iv_input', 'SOFA','reward']
data_CEL_selected = pd.read_csv("C:/Users/Public/CausalDM/causaldm/data/mimic3_CEL_selected.csv")
data_CEL_selected.pop(data_CEL_selected.columns[0])
data_CEL_selected

Glucose        paO2   PaO2_FiO2  iv_input  SOFA    reward
0         1.0    1.000000    1.000000       1.0     1  1.000000
1       122.0   59.444444  198.148148       0.0    12  0.383136
2       125.0  192.000000  690.647482       0.0     4  0.976040
3         1.0    1.000000    1.000000       1.0     1  1.000000
4         1.0    1.000000    1.000000       1.0     1  1.000000
...       ...         ...         ...       ...   ...       ...
4995      1.0    1.000000    1.000000       1.0     1  1.000000
4996    108.0   62.333333  143.846153       0.0    11 -0.025000
4997    106.0  258.500000  923.214286       0.0     7  0.402531
4998      1.0    1.000000    1.000000       1.0     1  1.000000
4999      1.0    1.000000    1.000000       1.0     1  1.000000

[5000 rows x 6 columns]

In [3]:
userinfo_index = np.array([0,1,2,4])
SandA = data_CEL_selected.iloc[:, np.array([0,1,2,3,4])]

In [4]:
# S-learner
S_learner = LGBMRegressor(max_depth=5)
#S_learner = LinearRegression()
#SandA = np.hstack((S.to_numpy(),A.to_numpy().reshape(-1,1)))
S_learner.fit(SandA, data_CEL_selected['reward'])

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=5,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [5]:
SandA_all1 = SandA.copy()
SandA_all0 = SandA.copy()
SandA_all1.iloc[:,3]=np.ones(n)
SandA_all0.iloc[:,3]=np.zeros(n)

HTE_S_learner = S_learner.predict(SandA_all1) - S_learner.predict(SandA_all0)


In [6]:
S_learner.predict(np.array([100,200,1000,1,5]).reshape(1, -1))

array([0.15234589])

In [7]:
S_learner.predict(np.array([100,200,1000,0,5]).reshape(1, -1))

array([0.15234589])

In [8]:
S_learner.predict(np.array([0,0,1000,0,5]).reshape(1, -1))

array([1.01825633])

Let's focus on the estimated HTEs for the first 8 patients:

In [9]:
print("S-learner:  ",HTE_S_learner[0:8])

S-learner:   [0. 0. 0. 0. 0. 0. 0. 0.]


**Conclusion:** Due to the difference of scales across state variables, S-learner failed to detect the heterogeneous treatment effect in this mimic3 dataset. Although it is the easiest approach to implement, the over-simplicity tends to cover some information that can be better explored with some advanced approaches.

## References
1. Kunzel, S. R., Sekhon, J. S., Bickel, P. J., and Yu, B. (2019). Metalearners for estimating heterogeneous treatment effects using machine learning. Proceedings of the national academy of sciences 116, 4156–4165.
